### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by tonylomax** [fac18/week3-DFJL-bday-time-machine#37]
Nice styling, cool design, can we re-factor this? - 

```css

.films__heading {
  color: white;
}

.films__title {
  color: white;
}

.films__date {
  color: white;
}

.films__overview {
  color: white;
}
```
